<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
	$IP = MW_INSTALL_PATH;
} else {
	$IP = dirname( __FILE__ );
}

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

require_once( "$IP/includes/DefaultSettings.php" );

# If PHP's memory limit is very low, some operations may fail.
ini_set( 'memory_limit', '50M' );

if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
}
## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename         = "Wiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "/mediawiki-1.13.5";
$wgScriptExtension  = ".php";

## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO

$wgEmergencyContact = "webmaster@localhost";
$wgPasswordSender = "webmaster@localhost";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = "localhost";
$wgDBname           = "wikidbTest1";
$wgDBuser           = "root";
$wgDBpassword       = "admin";

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = true;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads       = false;
# $wgUseImageMagick = true;
# $wgImageMagickConvertCommand = "/usr/bin/convert";

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
# $wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

$wgLocalInterwiki   = $wgSitename;

$wgLanguageCode = "en";

$wgProxyKey = "a065df9da3e361129d953ccd98f2893722a1791de40f1ddaa6a813a215ade160";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
$wgDefaultSkin = 'monobook';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
# $wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";
# $wgRightsCode = ""; # Not yet used

$wgDiff3 = "/usr/bin/diff3";

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$wgCacheEpoch = max( $wgCacheEpoch, gmdate( 'YmdHis', @filemtime( __FILE__ ) ) );

#semantic mediawiki
include_once("$IP/extensions/SemanticMediaWiki/includes/SMW_Settings.php");
enableSemantics($_SERVER['SERVER_NAME']);

require_once "$IP/extensions/p2pExtension/p2pExtension.php";

$wgGroupPermissions['*']['ArticleAdminPage']       = true;//sysop
require_once("$IP/extensions/p2pExtension/specialPage/ArticleAdminPage.php" );

$wgLogo = "{$wgScriptPath}/extensions/p2pExtension/files/Logo.jpeg";

# create namespace
define("PATCH",110);
define("PUSHFEED",200);
define("PULLFEED",210);
define("CHANGESET",220);

$wgExtraNamespaces[PATCH] = "Patch";
$wgExtraNamespaces[PUSHFEED] = "PushFeed";
$wgExtraNamespaces[PULLFEED] = "PullFeed";
$wgExtraNamespaces[CHANGESET] = "ChangeSet";
# protect namespace
$wgNamespaceProtection[PATCH] = Array("editpatch");
$wgNamespacesWithSubpages[PATCH] = true;
$wgGroupPermissions['*']['editpatch'] = false;
$wgGroupPermissions['sysop']['editpatch'] = true;
$wgNamespaceProtection[PUSHFEED] = Array("editpushfeed");
$wgNamespacesWithSubpages[PUSHFEED] = true;
$wgGroupPermissions['*']['editpushfeed'] = false;
$wgGroupPermissions['sysop']['editpushfeed'] = true;
$wgNamespaceProtection[PULLFEED] = Array("editpullfeed");
$wgNamespacesWithSubpages[PULLFEED] = true;
$wgGroupPermissions['*']['editpullfeed'] = false;
$wgGroupPermissions['sysop']['editpullfeed'] = true;
$wgNamespaceProtection[CHANGESET] = Array("editchangeset");
$wgNamespacesWithSubpages[CHANGESET] = true;
$wgGroupPermissions['*']['editchangeset'] = false;
$wgGroupPermissions['sysop']['editchangeset'] = true;

//semantic mediawiki extension
 $smwgNamespaceIndex = 120;

global $smwgNamespacesWithSemanticLinks;
$smwgNamespacesWithSemanticLinks = $smwgNamespacesWithSemanticLinks + array(
		PATCH => true,
		PUSHFEED => true,
        PULLFEED => true,
        CHANGESET => true
	);

//simple forms
$wgUseAjax = true;
include("$IP/extensions/SimpleForms/SimpleForms.php");
$wgSimpleFormsFormMagic = 'form';
$wgSimpleFormsInputMagic = 'input';
$wgSimpleFormsRequestMagic = 'request';
$wgSimpleFormsRequestPrefix;
$wgSimpleFormsAllowCreate = true;
$wgSimpleFormsAllowEdit = true;
$wgSimpleFormsAllowRemoteAddr = $IP;
$wgSimpleFormsServerUser;

$wgShowExceptionDetails = true;
