<?php




# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
	$IP = MW_INSTALL_PATH;
} else {
	$IP = dirname( __FILE__ );
}

#speed up jobs rate
$wgJobRunRate = 0.01;

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

require_once( "$IP/includes/DefaultSettings.php" );


if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
}
## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename         = "Dsmwdev";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "/mw1.16.4";
$wgScriptExtension  = ".php";

## The relative URL path to the skins directory
$wgStylePath        = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo             = "$wgStylePath/common/images/wiki.png";

## UPO means: this is also a user preference option

$wgEnableEmail      = false;
$wgEnableUserEmail  = false; # UPO

$wgEmergencyContact = "webmaster@localhost";
$wgPasswordSender = "webmaster@localhost";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = false;

$wgSitename=0;
$mysites=array(array('DsmwDev','mw1.16.4','wikidb','/mw1.16.4'),
               array('wiki1','wiki1','wikidbTest1','/wiki1'),
               array('wiki2','wiki2','wikidbTest2','/wiki2'),
               array('wiki3','wiki3','wikidbTest3','/wiki3'));
foreach($mysites as $site){
  if(strpos($_SERVER['SCRIPT_FILENAME'],$site[1])!==false){
    $wgSitename=$site[0];$wgDBname=$site[2];$wgScriptPath= $site[3];
;break;
  }
}
if(!$wgSitename && $wgCommandLineMode) {
#  foreach($mysites as $site){
#    if(strpos($_SERVER['PWD'],$site[1])!==false){
#      $wgSitename=$site[0];$wgDBname=$site[2];$wgScriptPath= $site[3];break;
#    }
#  }
      $site=$mysites[1] ; # wiki1
      $wgSitename=$site[0];$wgDBname=$site[2];$wgScriptPath= $site[3];
}

if(!$wgSitename){
  trigger_error('unknown DSMW server',E_USER_ERROR);
}

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = "localhost";
#$wgDBname           = "wikidb";
$wgDBuser           = "root";
$wgDBpassword       = "momo44";

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = true;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads       = true;
$wgUploadPath="{$wgScriptPath}/$wgDBname/images";
$wgUploadDirectory = "{$IP}/$wgDBname/images/";
$wgFileExtensions = array_merge($wgFileExtensions, array('doc', 'xls', 'mpp', 'pdf','ppt','xlsx','jpg','tiff'));

# $wgUseImageMagick = true;
# $wgImageMagickConvertCommand = "/usr/bin/convert";

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
# $wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgLocalInterwiki   = strtolower( $wgSitename );

$wgLanguageCode = "en";

$wgSecretKey = "9d94cefb0c9245b9ccc2f5d92142bb5f7bc95db9e5f82bd1176378d12b10ef24";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = 'monobook';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
# $wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";
# $wgRightsCode = ""; # Not yet used

$wgDiff3 = "/usr/bin/diff3";

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$wgCacheEpoch = max( $wgCacheEpoch, gmdate( 'YmdHis', @filemtime( __FILE__ ) ) );


#
# Debug config
# was hard to setup
# error reporting is on is php.ini (in /etc/php5/apache2 and /etc/php5/CLI
#
#error_reporting(-1);
#ini_set( 'display_startup_errors', 1);
#ini_set( 'display_errors', 1 );
#ini_set( 'error_reporting', E_ALL );

##$wgDebugLogFile='/tmp/dsmw.log';
##wfDebugLog('p2p','onskintemplat pouet');
$wgShowExceptionDetails = true;
$wgDebugToolbar = true;
$wgShowDebug = true;
$wgDebugComments=true;

##$wgShowSQLErrors = true;
##$wgDebugDumpSql  = true;
##$wgShowDBErrorBacktrace = true;

$wgDebugLogGroups = array(
        'p2p'     => '/tmp/dsmw.log',
        'anotherloggroup' => 'logs/another.log',
);



# parser function (used in wikitaaable)
require( "extensions/ParserFunctions/ParserFunctions.php");


# validator
require_once "$IP/extensions/Validator/Validator.php";

# DSMW
require_once "$IP/extensions/DSMW/DSMW.php";

#SMW
 include_once("$IP/extensions/SemanticMediaWiki/SemanticMediaWiki.php");
 enableSemantics($wgSitename);

